services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
volumes:
  oracle-data:
